### PR TITLE
Update composer with newer wpcs standards and rename the phpcs config file

### PR DESCRIPTION
**Pull request by dingo-d**
### Added:

* Additional composer fields in the `composer.json` file
* Added `dealerdirect/phpcodesniffer-composer-installer` plugin for manually setting the installed path of the standards and removed that line from the phpcs config.

I've also added some useful scripts for checking the coding standards:

```sh
composer check-cs src/
```

Will run `phpcs` with the default config on the `src/` folder.

There are number of PEAR error that should be fixed - 

```sh
PEAR.Functions.FunctionCallSignature.ContentAfterOpenBracket
PEAR.Functions.FunctionCallSignature.MultipleArguments
PEAR.Functions.FunctionCallSignature.CloseBracketLine
```

We can either ignore them in the config file or fix them automatically using `composer fix-cs src/` command.

### CODE REVIEW

**Comment by Clorith** [comment]
Would you please change the branch to `develop` before this can be implemented and reviewed, to suit the plugins new development flow.

**Comment by dingo-d** [comment]
@Clorith I've branched out of `master` branch, this seems to cause some conflicts. Should I fix this or wait for a review and then fix it?

**Comment by Clorith** [comment]
Fixing them is probably the best approach, `develop` is the one you want to be matched against (it also makes it cleaner to do the review if there's no conflicts to consider).

**Comment by dingo-d** [comment]
@Clorith I rebased on the develop branch (well tbh I first rebased without checking out the upstream branch, but we'll pretend that didn't happen 😄 🙈)

Can you check if everything is ok?

**Comment by Clorith** [comment]
Just an update that this hasn't been forgotten, I'll go over this once the UI/UX changes, and accessibility ones, have been finalized, as it will be easier to update coding standards once the code base isn't as much of a moving target as right now.

**Comment by Clorith** [comment]
This was resolved in 107e40d, closing the PR (since auto-close only happens when master is updated)

**Pull request closed without merging**
